<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SetupTest.fs" />
    <Compile Include="DatasetTest.fs" />
    <Compile Include="Chapter01/KinokoTakenokoTest.fs" />
    <Compile Include="Chapter01/KvsTDataTest.fs" />
    <Compile Include="Chapter02/RandomTest.fs" />
    <Compile Include="Chapter02/IrisPreprocessingTest.fs" />
    <Compile Include="Chapter02/IrisDataTest.fs" />
    <Compile Include="Chapter03/DecisionTreeTest.fs" />
    <Compile Include="Chapter03/MlNetAdapterTest.fs" />
    <Compile Include="Chapter03/IrisDataTest.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MachineLearning\MachineLearning.fsproj" />
  </ItemGroup>

</Project>
