<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Dataset.fs" />
    <Compile Include="Chapter01/KinokoTakenoko.fs" />
    <Compile Include="Chapter01/Main.fs" />
    <Compile Include="Chapter02/Random.fs" />
    <Compile Include="Chapter02/IrisPreprocessing.fs" />
    <Compile Include="Chapter02/Main.fs" />
    <Compile Include="Chapter03/DecisionTree.fs" />
    <Compile Include="Chapter03/MlNetAdapter.fs" />
    <Compile Include="Chapter03/Main.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="FSharp.Stats" />
    <PackageReference Include="Microsoft.ML" />
    <PackageReference Include="Microsoft.ML.FastTree" />
  </ItemGroup>

</Project>
