<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Dataset.fs" />
    <Compile Include="Chapter01/KinokoTakenoko.fs" />
    <Compile Include="Chapter01/Main.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
